### ISSUE TITLE
Add support for hair color

### ISSUE THREAD

**Issue by mul1sh** [jtouzy/vue-avataaar#3]
@jtouzy thanks for this really cool library, been using it in some of my projects and I like it alot.

Anyway I was wondering if you could also add support for the `hairColor` property too since its already supported in the react component.  

I could also do a PR to support this if you don't mind

**Comment by jtouzy** [comment]
Hi mul1sh !
I think I just forgot the hairColor property. 
I will implement this tonight. I'll keep you informed.

**Comment by mul1sh** [comment]
Perfect thanks 🙂

**Comment by mul1sh** [comment]
@jtouzy thanks for implementing this feature, it works perfectly. So i'll close this issue then :)

**Comment by jtouzy** [comment]
FYI i'm gonna push another release to include this. Thanks for report ;)

**Comment by mul1sh** [comment]
@jtouzy thanks 🙂

**Comment by jtouzy** [comment]
@mul1sh Release published (0.2.0).
