### ISSUE TITLE
Color Fabric Missing

### ISSUE THREAD

**Issue by maciz84** [jtouzy/vue-avataaar#4]
Please add Color Fabric property

Great little library 👍

**Comment by maciz84** [comment]
Any update on this?

**Comment by jtouzy** [comment]
Sorry for the delay, i’m a little busy right now. 
What do you mean by Color Fabric ?

**Comment by maciz84** [comment]
Hi @jtouzy . Sorry to hear that you are busy. What  I mean by this is the option to change the color of the clothing. That property is available on the avataar site https://getavataaars.com/. IT seems to be available when you choose certain clothes like a hoodie etc.

I hope that helps

**Comment by maciz84** [comment]
The property name is clotheColor...I think

**Comment by maciz84** [comment]
The  colors are below:
Black
Blue01
Blue02
Blue03
Gray01
Gray02
Heather
PastelBlue
PastelGreen
PastelOrange
PastelRed
PastelYellow
Pink
Red
White

**Comment by jtouzy** [comment]
Okay i see.
I'm working on a rewrite of this lib to generate svg images instead of calling an url.
This property has already been added.
I'll inform you when i'll release the new lib version.

**Comment by maciz84** [comment]
Excellent @jtouzy thank you for making the library it is really cool. Keep up the good work and I look forward to playing with the new version when released 👍

**Comment by jtouzy** [comment]
Sorry, right now i don't have time to work on the full-SVG release, but i've updated the current library version with missing colorFabric & graphic properties (0.3.0). Enjoy !

**Comment by maciz84** [comment]
@jtouzy thank you for updating the library. I however cannot get the clotheColor and graphicType properties to work. Below is the img url that I have inspected in the debugger. It looks like the two new properties are being added outside of the image url itself or something like that.

"https://avataaars.io?avatarStyle=Circle&amp;accessoriesType=Blank&amp;clotheType=BlazerShirt&amp;eyebrowType=Default&amp;eyeType=Default&amp;facialHairColor=Brown&amp;facialHairType=Blank&amp;hairColor=Brown&amp;mouthType=Default&amp;skinColor=Tanned&amp;topType=NoHair" clothecolor="PastelGreen" graphictype="Skull"

When you have a moment could you please try and have a look at it.

**Comment by jtouzy** [comment]
Do you have 0.3.1 version ?
Yesterday i published 2 versions because in the first one, property names were bad named.
I use the component like this and this works :

`<avataaar :width="avatarWidth" class="mr-3"
            avatar-style="Circle"
            :accessories-type="accessoriesType"
            :clothe-type="clotheType"
            :clothe-color="clotheColor"
            :eye-type="eyeType"
            :eyebrow-type="eyebrowType"
            :facial-hair-type="facialHairType"
            :facial-hair-color="facialHairColor"
            :graphic-type="graphicType"
            :hair-color="hairColor"
            :mouth-type="mouthType"
            :skin-color="skinColor"
            :top-type="topType">`

**Comment by maciz84** [comment]
Oh no I have 0.3.0

**Comment by maciz84** [comment]
Ok I will update now to 0.3.1 and let you know 👍

**Comment by maciz84** [comment]
Ok I have updated and voila it works. Thank you so much again you are a legend 🥇
